# RP2040-specific options
ALLOW_WARNINGS = yes
PICO_INTRINSICS_ENABLED = no # ATM Unsupported by ChibiOS.
BOARD = GENERIC_RP_RP2040
SWAP_HANDS_ENABLE = no

SERIAL_DRIVER = vendor

TAP_DANCE_ENABLE = yes

OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c

ENCODER_ENABLE = no

ENCODER_MAP_ENABLE = yes


PIN_COMPATIBLE = elite_c
CONVERT_TO=elite_pi
